"""fix

Revision ID: 98e48e22bde5
Revises: ff3182186b86
Create Date: 2026-06-24 02:15:56.440178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e48e22bde5'
down_revision: Union[str, Sequence[str], None] = 'ff3182186b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_workout_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'workout_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_workout_id_fkey'), 'user', 'workout', ['workout_id'], ['id'])
    # ### end Alembic commands ###
